import streamlit as st
from st_tldraw import tldraw

ini = '{"document":{"store":{"document:document":{"gridSize":10,"name":"","meta":{},"id":"document:document","typeName":"document"},"page:page":{"meta":{},"id":"page:page","name":"Page 1","index":"a1","typeName":"page"},"shape:POApENvmFmVO-O8m_-MBu":{"x":237.2000608444214,"y":165.7999906539917,"rotation":0,"isLocked":false,"opacity":1,"meta":{},"id":"shape:POApENvmFmVO-O8m_-MBu","type":"arrow","props":{"kind":"arc","elbowMidPoint":0.5,"dash":"dashed","size":"m","fill":"semi","color":"black","labelColor":"black","bend":206.02282797270712,"start":{"x":0,"y":0},"end":{"x":98.39999389648438,"y":135.20001220703125},"arrowheadStart":"none","arrowheadEnd":"arrow","richText":{"type":"doc","content":[{"type":"paragraph"}]},"labelPosition":0.5,"font":"draw","scale":1},"parentId":"page:page","index":"a1BfaALV","typeName":"shape"}},"schema":{"schemaVersion":2,"sequences":{"com.tldraw.store":5,"com.tldraw.asset":1,"com.tldraw.camera":1,"com.tldraw.document":2,"com.tldraw.instance":26,"com.tldraw.instance_page_state":5,"com.tldraw.page":1,"com.tldraw.instance_presence":6,"com.tldraw.pointer":1,"com.tldraw.shape":4,"com.tldraw.asset.bookmark":2,"com.tldraw.asset.image":5,"com.tldraw.asset.video":5,"com.tldraw.shape.group":0,"com.tldraw.shape.text":4,"com.tldraw.shape.bookmark":2,"com.tldraw.shape.draw":4,"com.tldraw.shape.geo":11,"com.tldraw.shape.note":10,"com.tldraw.shape.line":5,"com.tldraw.shape.frame":1,"com.tldraw.shape.arrow":8,"com.tldraw.shape.highlight":3,"com.tldraw.shape.embed":4,"com.tldraw.shape.image":5,"com.tldraw.shape.video":4,"com.tldraw.binding.arrow":1}}},"session":{"version":0,"currentPageId":"page:page","exportBackground":true,"isFocusMode":false,"isDebugMode":false,"isToolLocked":false,"isGridMode":false,"pageStates":[{"pageId":"page:page","camera":{"x":0,"y":0,"z":1},"selectedShapeIds":["shape:POApENvmFmVO-O8m_-MBu"],"focusedGroupId":null}]}}'

with st.form("config"):
    pk = st.text_input("Persistence Key", "key1")
    submit = st.form_submit_button("Apply")
# pk = st.text_input("Persistence Key", 'key1')
data = tldraw(ini, persistenceKey=pk)
st.write(data)